### PR TITLE
Change display of date and time to match system

### PR DESCRIPTION
**Pull request by TiiXel**
Some users located in places where time and date are not displayed as
YYYY/MM/DD HH/MM A might want to have the app displays match their
system settings.

### CODE REVIEW

**Comment by MTBehnke** [comment]
Issue #44 was a crash report in ObservationAddFragment related to JodaTime.  Not sure if this is related and/or also potentially solves or also causes crash.  Only affected one user so far.

**Comment by TiiXel** [comment]
I forgot to change rise/set times in the DSObject page! Will do soon.

**Comment by MTBehnke** [comment]
I branched the master ('Transit') and pushed a fairly complete commit with changes to the DSObject page with a separate section for Rise, Transit and Set Times + Transit Altitude.  We might want to merge your pull request that addresses the observation add and edit fragments into the master, then have you or I edit the transit branch to include your time formatting changes in the Transit branch.

**Comment by TiiXel** [comment]
I'll look at it ! That would be a good way to manage the changes I guess.

**Comment by TiiXel** [comment]
This should fix  rise/set times formatting in the DSObject page.

**Pull request merged**
